services:
  - type: web
    name: certnode-backend
    env: python
    rootDir: backend
    buildCommand: ""
    startCommand: python main.py
    preDeployCommand: pip install -r backend/requirements.txt
    autoDeploy: true
    region: oregon
    plan: free
