services:
  - type: web
    name: certnode-backend
    env: python
    rootDir: frontend/customer-portal
    buildCommand: ""
    startCommand: python main.py
    preDeployCommand: pip install -r requirements.txt
    autoDeploy: true
    region: oregon
    plan: free
