name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Fast tests
        run: node tools/test-fast.js

      - name: Pack Node SDK
        working-directory: sdk/node
        run: npm pack --json

      - name: Pack Web SDK
        working-directory: sdk/web
        run: npm pack --json

      - name: JWKS integrity (examples)
        run: node tools/jwks-integrity-check.js --jwks examples/jwks.example.json

      - name: JWKS rotation overlap (examples)
        run: node tools/jwks-rotate-validate.js --current examples/jwks.example.json --next examples/jwks.example.json

      - name: OpenAPI quick check
        run: node tools/check-openapi.js

      - name: Commit message lint (non-strict)
        run: node tools/commit-lint.js || true

      - name: Docker build
        run: docker build -t certnode:ci .

  commit-lint-pr:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Commit message lint (strict)
        run: node tools/commit-lint.js --strict
