name: infra-drift
on:
  schedule: [{ cron: "17 3 * * *" }]  # daily 03:17 UTC
  workflow_dispatch: {}

jobs:
  drift:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    env:
      TF_DIR: infra/aws/terraform
      AWS_REGION: us-east-1
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      TF_STATE_TABLE:  ${{ secrets.TF_STATE_TABLE }}
      TF_STATE_KEY:    envs/prod/terraform.tfstate
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - name: Init backend
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_STATE_TABLE }}" \
            -backend-config="encrypt=true"
      - name: Plan (capture exit code)
        id: plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          set +e
          terraform plan -detailed-exitcode -no-color -input=false
          ec=$?
          echo "exitcode=$ec" >> "$GITHUB_OUTPUT"
          exit 0
      - name: Fail if drift
        if: steps.plan.outputs.exitcode == '2'
        run: exit 1

