name: CI / Infra Check

on:
  pull_request:
    paths:
      - "infra/aws/terraform/**"
      - ".github/workflows/infra-check.yml"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/aws/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "~1.8"

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan (smoke)
        run: terraform plan -input=false -no-color

