name: infra-plan
on:
  pull_request:
    paths: ["infra/aws/terraform/**"]

env:
  TF_DIR: infra/aws/terraform
  AWS_REGION: us-east-1
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
  TF_STATE_TABLE:  ${{ secrets.TF_STATE_TABLE }}
  TF_STATE_KEY:    envs/staging/terraform.tfstate

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }

      - name: Init (remote backend)
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_STATE_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Plan
        id: plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -no-color -input=false -out=plan.bin | tee plan.txt

      - name: Comment plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: infra/aws/terraform/plan.txt

