name: No conflict markers
on: [push, pull_request]
jobs:
  grep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: '! (git grep -nE "<<<<<<< |=======|>>>>>>>" -- . || true)'

