name: Publish Node SDK (manual)

on:
  workflow_dispatch:
    inputs:
      forcePublish:
        description: 'Force publish even if version seems present'
        required: false
        default: 'false'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@certnode'
          always-auth: true

      - name: Assert NPM_TOKEN present
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "${NPM_TOKEN}" ]; then
            echo 'NPM_TOKEN GitHub secret is missing. Add it in repo Settings → Secrets → Actions.' >&2
            exit 1
          fi

      - name: NPM debug
        run: |
          node --version | sed 's/^/node: /'
          npm --version | sed 's/^/npm:  /'
          printf "registry: "; npm config get registry
          printf "pkg-name: "; node -p "require('./sdk/node/package.json').name"
          printf "pkg-ver:  "; node -p "require('./sdk/node/package.json').version"
          npm whoami || true

      - name: Prime npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "$HOME/.npmrc"
          chmod 600 "$HOME/.npmrc"

      - name: Precheck version
        id: pre
        shell: bash
        run: |
          PKG='@certnode/sdk'
          VER=$(node -p "require('./sdk/node/package.json').version")
          echo "ver=$VER" >> $GITHUB_OUTPUT
          EXISTS=$(npm view "$PKG@$VER" version 2>/dev/null || true)
          if [ "$EXISTS" = "$VER" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Pack
        working-directory: sdk/node
        run: npm pack --json

      - name: Publish
        if: steps.pre.outputs.exists == 'false' || inputs.forcePublish == 'true'
        working-directory: sdk/node
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public

      - name: Verify
        shell: bash
        run: |
          PKG='@certnode/sdk'
          VER=$(node -p "require('./sdk/node/package.json').version")
          for i in {1..30}; do
            P=$(npm view "$PKG@$VER" version 2>/dev/null || true)
            if [ "$P" = "$VER" ]; then
              echo "Published $PKG@$VER"
              exit 0
            fi
            sleep 6
          done
          echo "Publish not visible on npm after timeout" >&2
          exit 1
