name: Smoke trust+spec endpoints
on: [push]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: JWKS headers
        run: curl -fsSI https://certnode.io/.well-known/jwks.json | grep -i "application/jwk-set+json"
      - name: Rotation log headers
        run: curl -fsSI https://certnode.io/trust/keys.jsonl | grep -i "application/json"
      - name: OpenAPI JSON
        run: |
          curl -fsS https://certnode.io/openapi.json | jq -e '.openapi|startswith("3.")'

